version: '3'

services:
  doctor-labelling-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_dev_doctor_labelling
      - MYSQL_USER=usertestdoctorlabelling
      - MYSQL_PASSWORD=123456
    ports:
      - 3308:3306

  doctor-labellingapp:
    image: doctor/labelling
    ports:
       - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://doctor-labelling-mysql:3306/db_dev_doctor_labelling?autoReconnect=true&useSSL=false
    depends_on:
       - doctor-labelling-mysql